import removeExtension from "./removeExtension";

// generated by bash script
const imageNames = [
  "1table_JOOLA CITY OUTDOOR TABLE TENNIS TABLE_2199.00.jpg",
  "1table_JOOLA CITY OUTDOOR TABLE TENNIS TABLE_625.00.jpg",
  "1table_JOOLA J15 INSIDE TABLE TENNIS TABLE_599.00.jpg",
  "2pat_BRIBAR PRO OFFENSIVE LIGHT TABLE TENNIS BAT_109.99.png",
  "2pat_BRIBAR RALLY TABLE TENNIS BAT WITH FREE BAT CASE_29.99.png",
  "2pat_JOOLA FUN TABLE TENNIS BAT_4.99.jpg",
  "3balls_DOUBLE FISH V40+ 3* NEW GENERATION TABLE TENNIS BALL_9.99.png",
  "3balls_GEWO 3* TRAINING 40+ TABLE TENNIS BALLS_6.99.jpg",
];

const getData = () =>
  imageNames.map((item, index) => {
    const attributes = removeExtension(item).split("_");
    return {
      src: require(`../assets/items/${item}`),
      name: attributes[1],
      price: attributes[2],
      inCart: 0,
      id: index,
    };
  });

export default getData;
